# Generated by Django 4.1.4 on 2023-01-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='name',
            field=models.CharField(default='abc', max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
