# Generated by Django 4.1.4 on 2023-01-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_category_name_items_description_items_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
